### ISSUE TITLE
Javadoc for Objectify.transactnew wrong

### ISSUE THREAD

**Issue by kronrod** [objectify/objectify#260]
Objectify.transactNew(int limitTries, Work work) if documented as follows "Executes the work in a new transaction, repeating up to limitTries times when a ConcurrentModificationException is thrown.  This requires your Work to be idempotent; otherwise limit tries to 1."

However, this conflicts with the actual implementation which does not treat "limitTries" as the number of repetitions in total, but as the numer of retries. The correct documentation should read as follows: "Executes the work in a new transaction, **retrying** up to limitTries times when a ConcurrentModificationException is thrown.  This requires your Work to be idempotent; otherwise **set limitTries to 0**."

Note that the phrase "n repetitions" should be avoided alltogether, as people sometimes interpret this as "n executions in total", and sometimes as "n executions on top of the first".

**Comment by stickfigure** [comment]
Wow. I'm going to change the behavior, not the documentation, because I'm fairly certain that most people who are using that method are expecting the documented behavior and simply getting a risk of an extra retry.

That said, there probably aren't many people using this method - it's fairly obscure. Thanks for catching that!

**Comment by tj-recess** [comment]
Perhaps we should rename word 'retry' to 'attempt' in documentation which would make intention clearer.

**Comment by kronrod** [comment]
Thanks!
