### ISSUE TITLE
how to change default objectify memcache namespace?

### ISSUE THREAD

**Issue by samodadela** [objectify/objectify#301]
Hi, 

I want to run some tests in 'isolation' (at least datastore and memcache) using a different namespace. 

Now to change the DS namespace I used NamespaceManager.set("testing") but I think I still need to change Objectify's memcache so that the memcache is not shared between "testing" and "default". 

I found this:

```
public class ObjectifyFactory implements Forge
{
	/** Default memcache namespace; override getRawMemcacheService() to change */
	public static final String MEMCACHE_NAMESPACE = "ObjectifyCache";
```

Problem is getRawMemcacheService() does not exists anymore(?) (the only mention of it is in this comment). If the comment is wrong, it should be changed.

Can someone point me to the correct way to change both DS and memcache in objectify? I'm currently accessing objectify like this:

```
public class OfyService {

    static {
        ObjectifyService.register( XYZ.class );
    }

    public static Objectify ofy() {
        return ObjectifyService.ofy();
    }
}
```

And then the static import:

`import static my.package.OfyService.ofy;
`

As said I need this just for testing... I think it should work as long as I'm using it only for the datastore and memcache... but please enlighten me to the possible problems this can cause.

Best regards, 

Samo

**Comment by stickfigure** [comment]
This is really a question for the Google Group or Stackoverflow - the issue tracker is a bad place to ask questions. You're right, there's no convenient way to do this right now (although you could override `createAsyncDatastoreService()` in its entirety and the javadoc is incorrect.

However, it sounds like you're doing something horribly wrong by trying to use namespaces to isolate test data from regular data. And there's not much point in isolating memcache since every key uniquely contains its namespace and therefore there is no risk of collisions. For further questions, please use the Google Group (or SO) - if we establish that there's a compelling reason to be able to swap the namespaces, we can reopen this issue and I'll make the code more flexible.

**Comment by samodadela** [comment]
I already checked GG and SO and found no conclusive answer (one said to just use NamespaceManger.set(), the other to override some objectify method), so I tried the instructions from  ObjectifyFactory.java. 

The missing piece was your statement "And there's not much point in isolating memcache since every key uniquely contains its namespace and therefore there is no risk of collisions". I guess this is an objectify thing because with the native memcache API the key can be anything. 

As for doing something wrong: you're probably right, but I'm not feeling the horror, yet ;) This is all pre-production and I just need a quick & dirty way to separate data without having to rename entities or adding fields to mark data as 'testing'.

If possible, please correct the comment in ObjectifyFactory.java.

You're answer helped a lot.

Thanks
