### ISSUE TITLE
gae version 1.9.50

### ISSUE THREAD

**Issue by elharo** [objectify/objectify#324]
Currently pom.xml has 1.9.24, very out of date.

		<gae.version>1.9.24</gae.version>

**Comment by stickfigure** [comment]
This is somewhat deliberate... my preference would be to rely on the oldest version of the SDK that is compatible with Objectify. We don't want to force upgrade people.

It doesn't matter in practice because nobody should rely on a transitive dependency from Objectify to pull in the GAE sdk. You use GAE SDK code in your app, you should have a direct dependency with a specific version of the SDK.

Maybe the right answer is to make that dependency <scope>provided</scope>?
