### ISSUE TITLE
Use Servlet 3.0 annotations

### ISSUE THREAD

**Issue by billy1380** [objectify/objectify#331]
Now that we have java 8 on appengine: sould there be a java8 branch to migrate things e.g the filter added to web.xml to servlet 3 API? And maybe other bits too (not exactly sure what though).

**Comment by Oziomajnr** [comment]
I think this should be given priority as Google App Engine java 7 runtime is deprecated and  from January 2019 all projects using the java 7 runtime would be migrated to Java 8.

**Comment by stickfigure** [comment]
Objectify is already Java8 only and makes heavy use of Java8 features like closures and streams.

I'm going to rename this issue to "use Servlet 3.0 annotations" since that seems to be the specific item brought up. If there are other specific Java8 issues, please file additional issues.

**Comment by stickfigure** [comment]
There are a couple problems with using Servlet 3.0 annotations:

 * There's no way to specify order. If you use Objectify in other filters, your app will randomly work or not work depending on how the container sets them up.
 * Not everyone has the same mapping; it isn't necessarily going to be on `/*`
 * We can't force everyone to use the ObjectifyFilter. Maybe someone is using Objectify only with the Remote API; they don't want the filter.
 * I believe using Servlet 3.0 features triggers classpath scanning and likely slows app startup. Some people are rather sensitive to this.

It doesn't seem like there's a strong case for adding the Servlet 3 annotations since you need to modify web.xml anyway.

**Comment by billy1380** [comment]
I added this class to my project and removed all changes from the web.xml file

``` java
@WebFilter(filterName = "ObjectifyFilter", urlPatterns = "/*")
public static final class PersistenceFilter extends ObjectifyFilter {}
```

I can see why baking it straight into the framework might be a mistake.

**Comment by stickfigure** [comment]
I'm calling that a great solution :-)
