### ISSUE TITLE
Potential issue w/ compatibility with GAE framework 2.0

### ISSUE THREAD

**Issue by FlyingRam** [objectify/objectify#344]
I recently switched my gae framework to 2.0 with Objectify 5.1.21.

I notice that in the scenario of multi-filter on a list of objects, the cursor always return null for some reason. 

I have opened an issue w/ Google, but they think the problem is w/ Objectify.

Has anyone run into the same issue?

**Comment by stickfigure** [comment]
What is "gae framework 2.0"? The latest version I see is 1.9.59.

**Comment by stickfigure** [comment]
That's Google Cloud Endpoints. Objectify has no dependency on endpoints and is not related to endpoints in any way. If there is some sort of deeper issue with the underlying system, it isn't Objectify's doing :-/

Are you sure cursors when multi-filtering a list of objects worked before? Because if that changed, it's something in Google's low level SDK. But it also wouldn't surprise me if cursoring an IN filter was never supported.
