### ISSUE TITLE
Documentation on @Cache is misleading

### ISSUE THREAD

**Issue by heigov** [objectify/objectify#352]
In the "Caching" documentation it says:

> Writes will "write through" the cache to the datastore. Performance is only improved on read-heavy applications.

What does "write through" exactly mean? As I would understand it is if you save() an entity it would also write the new value to the Memcache. But actually it deletes the entity from cache. To get it back into the cache you would need to do the load() operation.

**Comment by stickfigure** [comment]
I agree, too ambiguous. I've updated that section of the docs to say:

  * Writes (`save()` and `delete()`) clear cache entries. Loads read and (on miss) populate the cache.  Performance is only improved on read-heavy applications.

Good enough?

It's not literally true since we actually put a meaningless value instead of clearing (this is needed for CAS operations), but it's conceptually how it works.

**Comment by heigov** [comment]
Thanks, this makes the documentation more accurate.

But I still do not understand why would you put a meaningless value in the cache instead of the new updated value?
In my usecase I am saving an object in the Datastore and then later when I need to update a few properties I would get the object from Datastore, perform mutations and save it again. It would be great that when I save it then the cache would also be updated with the new value, so that the next time I need to update a property I could get the current state from the cache already.

**Comment by stickfigure** [comment]
It's been a very long time since I worked through the logic, but the upshot is that it is much harder to achieve transactional consistency when writing to the cache on save. It requires comparing an authoritative timestamp on the entity itself, which wasn't part of the GAE API when this code was written. And although it was added later, this is not part of the API surface of the new cloud SDK.
