### ISSUE TITLE
Objectify v6 @Serialize on a List property doesn't seem to imply @Unindex

### ISSUE THREAD

**Issue by frew** [objectify/objectify#390]
We ran into a problem migrating to Objectify v6 where we were getting "Cannot index property >1500 characters" errors on a property that is @Serialize List<{Serializable class}> - adding @Unindex fixed the issue but seems like that should be implied since I doubt there's a useful way to index a serialized property?

**Comment by stickfigure** [comment]
Wow this is an interesting question. While it seems odd, it _might_ make sense to index a short serialized blob to perform equality tests? I would hate to answer the poor guy who's wondering why his `@Index @Serialize` field doesn't show up in search results...

I guess this was a moot issue in Objectify v5 because `Blob` was automatically excluded from indexes. The datastore now allows indexing Blobs. My gut sense is that "you asked for it, you should get it" - is it a problem to add @Unindex to your serialized fields?

**Comment by frew** [comment]
Nah, not a problem for us. Was mostly just surprised it was possible. Yeah, I buy the "you asked for it, you should get it" argument. Maybe add to the V5toV6 changes list and call it a day?

**Comment by stickfigure** [comment]
Good plan, will do.
