### ISSUE TITLE
Are objectify query results being session cached?

### ISSUE THREAD

**Issue by Malleswari103095** [objectify/objectify#391]
Hi, I've encountered a strange issue recently with Objectify query results. To be more precise, I explain the scenario with an use case. 

Note : All the below mentioned operations happened in the **same request session**. 

I have an `User` entity, which has a cache expiration set to 24 hours `@Cache(expirationSeconds = 86400)`

I tried fetching recently modified `User` entities with following query in the given time range : 
```
ObjectifyService.ofy().load().type(User.class)
                             .filter("modifiedAt >", 1000L)
                             .filter("modifiedAt <=", 1005L)
                             .limit(5).order("modifiedAt").list();
```
I got 3 entries which are matched with the query. The sample result is as follows : 
```
[
  {
    "id" : 123,
    "name" : "Bob",
    "modifiedAt" : 1002
  },
  {
    "id" : 456,
    "name" : "John",
    "modifiedAt" : 1003
  },
  {
    "id" : 789,
    "name" : "Max",
    "modifiedAt" : 1004
  }
]
```
Meanwhile, `John` has updated his name to `Johnathan` at 1007 (timestamp) and `modifiedAt` got changed to 1007. Now, I tried to fetch the entities with the following query : 
```
ObjectifyService.ofy().load().type(User.class)
                             .filter("modifiedAt >", 1006L)
                             .filter("modifiedAt <=", 1010L)
                             .limit(5).order("modifiedAt").list();
```
Now, the expected result should be 1 entity, which got recently modified by John. However, I got the result as following : 
```
[
  {
    "id" : 456,
    "name" : "John",
    "modifiedAt" : 1003
  }
]
```
The entity resulted has the same old values of previous fetch query. It should have updated name as `Johnathan` and updated timestamp as 1007, but it's not. Can you tell me is this happening because of **session cache**?

Thanks.

**Comment by stickfigure** [comment]
Since you say this is happening in the same request session, yes, this is the session cache at work. 

See: https://github.com/objectify/objectify/wiki/Caching

Note that the `@Cache` annotation only affects the global memcache. It is unrelated to the session cache.

You can clear the session cache with `ofy().clear()`.

**Comment by Malleswari103095** [comment]
Hi @stickfigure Thanks for the quick response. I understand the session caching, however, query results are not intended to be cached and provide the stale results.

If you see my example, I had two different queries with different timestamps, where it matches the query with updated value, but returns the old/cached values. This is leads to a problem, we end up in having the invalid data.

Either query shouldn't match against the cached data, or if it matches, it should give up to date results.

I would like to understand how it's useful, if this has been made with intention. 

Thanks for you time, 
Have a good day!

**Comment by stickfigure** [comment]
This is 100% intentional and it matches the behavior of JPA and JDO sessions. The data accessed in a session is intended to be as consistent as possible; an entity loaded is always the same instance. You can imagine a transaction that spans multiple methods; if methodA loads and modifies an entity, methodB should see that same change. Also, this allows you to perform object identity equality comparisons on entities.

It sounds like you want to have multiple sessions. You can do this; see `ObjectifyService.run()` (or `begin()`). However, this could very well be a code smell. What exactly are you trying to do?

**Comment by stickfigure** [comment]
I should also add: Even if you have multiple separate sessions, you are not guaranteed to see the change to 1007 in the second query. Because of eventual consistency, you may get an empty result set (the index may not have been updated yet).
