### ISSUE TITLE
Everything correct with the legacy WebSafeString-Keys?

### ISSUE THREAD

**Issue by DerKeil** [objectify/objectify#410]
I am working with Objectify 6.0.2 and I have two questions:

1) The method `Key.toWebSafeString()` states it "is an alias for toLegacyUrlSafe()", but actually it implements the new method `toUrlSafe()`. This is wrong, or am I confused?

2) The `KeyFormat`-class, which converts-to or reads-from the legacy webSafeString-Keys, suggests that the projectId always starts with an "s~". But this is not correct. Maybe it is correct for all US-projects, but I am having a Europe-project, which starts with an "e~". For that project the methods `KeyFormat.formatOldStyleAppEngineKey()` and `KeyFormat.parseOldStyleAppEngineKey()` are wrong.

Best
Stefan

**Comment by stickfigure** [comment]
Ugh. Well, this is a dilemma.

`Key.toWebSafeString()` existed for backwards compatibility with the old Objectify 5. So the documentation is correct, but the behavior is wrong. Incorrectly fix the documentation or correctly fix the behavior? It's a deprecated method so folks shouldn't be using it unless they're expecting the legacy key... but they haven't been getting it. What do you think?

Re #2, Let me loop in @frew who understands the KeyFormat behavior better than I.

**Comment by frew** [comment]
Oh, hah. Yes. The key prefix stuff is a trash fire. Do the new-style keys for Cloud Datastore omit the e~ prefix like they do the s~ prefix? (i.e. if you fetch a key using the new datastore api directly and do `getProjectId()` does it have the e~ ?) If so, the fix for `parseOldStyleAppEngineKey()` seems pretty straightforward - since ~ isn't valid in a project id, we can just drop any [letter]~ prefix. `formatOldStyleAppEngineKey` is trickier. Do you know if there's anything in the environment to tell us whether to use `s~` or `e~`? If not obvious, I can ping the app engine team and see if they have any ideas.

**Comment by DerKeil** [comment]
@stickfigure Simply remove `Key.toWebSafeString()` in the next version of Objectify? There is a lot that changes from Objectify 5 to 6, so it is ok if people have to rethink what they do with their previous webSafe-Keys.

@frew As it seems the prefix `e~` is ommited when asking the projectId of a `com.google.cloud.datastore.BaseKey`. But I have no clue how to fix  `formatOldStyleAppEngineKey`.

**Comment by stickfigure** [comment]
Removed the deprecated toWebSafeString() and getString() methods
