### ISSUE TITLE
jackson-core isn't really optional:

### ISSUE THREAD

**Issue by elharo** [objectify/objectify#422]
The pom.xml for Objectify 6.0 declares jackson-core as optional:

```
	<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.9.1</version>
			<scope>compile</scope>
			<optional>true</optional>
		</dependency>
```

However, the transitive dependencies in google-cloud-datastore have a non-optional dependency on this artifact. This dependency can shadow those dependencies and thus prevent this artifact from being added to the classpath when it is needed. This is not a problem for straight Maven but M2E gets confused here. 

Arguably this is a bug in M2E. However since this will be in the CLASSPATH anyway, we might as well mark it non-optional here.

**Comment by stickfigure** [comment]
Hmmmmm. Just because there is a transitive link today doesn't mean there will always be one. This feels like working around a bug in M2E by adding a bug in the data structure, which seems worse to me.

I made one change that *might* help, depending on the nature of the M2E bug. I moved the google-cloud-datastore artifact declaration ahead of the optional declarations in the Objectify pom. Maybe it's just a traversal ordering issue?
