### ISSUE TITLE
Queries are not respecting chunk-size

### ISSUE THREAD

**Issue by DerKeil** [objectify/objectify#443]
Hey,
the chunk-size you specify via
ofy().load().type(Bla.class).filter(...)
					.limit(limit)
					.chunk(chunk)
					.list();
is NOT considered, as internally it is always set to 1000 again.

In QueryImpl.list() it is first set to Integer.MAX_VALUE and in HybridQueryResults.safePartition() it is set to 1000 afterwards.

**Comment by stickfigure** [comment]
The idea here is that if you're fetching the whole list (rather than iterating), we might as well use the largest chunk size we can. Interesting that this is causing a problem with Refs.

If you want immediate satisfaction, call `Lists.newArrayList(ofy()...iteratable())` - chunk size is respected when getting an Iterable or Iterator. Or you can wait for the next release (today). I'm going to disable the maximize-chunk-size-for-lists code so that `list()` obeys the chunk size request. If we sort out the ref issue at a later date we can undo this.

**Comment by stickfigure** [comment]
I fixed the other issue so I reverted this change - `list()` now maximizes chunk-size again. If you really want fine control, use `iterator()` or `iterable()`
