### ISSUE TITLE
Objectify 5 and Google Standalone App Engine SDK deprecation

### ISSUE THREAD

**Issue by sinogermany** [objectify/objectify#456]
Hi Objectify community,

Thanks for building the awesome product and making Datastore operations much more intuitive. Very much appreciated!

Looks like Google has a [timeline for deprecating the Standalone App Engine SDK](https://cloud.google.com/appengine/docs/standard/java/sdk-gcloud-migration). 

According to that timeline, here's what's going to happen with the Standalone App Engine SDK:

| Date                      | Action                    | 
| ----------------- | ----------------- |
| July      30, 2019  | The standalone App Engine SDK-based tooling is deprecated. |
| August 30, 2020 | The standalone App Engine SDK will not be available for download and might not work, if used. |
| August 30, 2020 | Google shuts down and removes support for the standalone App Engine SDK. |

What does that mean for Objectify 5? Does it mean we either point to a repository with the SDK jar or do we plan to EOL Objectify 5?

Thanks a lot and stay safe ~

**Comment by stickfigure** [comment]
That is just the SDK tooling - not the APIs. So if you're using the old
maven plugin, you need to move to the new one. Otherwise you shouldn't see
any change.

There has not yet been any kind of deprecation announcement for the
"classic" GAE APIs (which Ofy5 uses). If I had to guess, I bet they be shut
down at the same time that the Java8 runtime is shut down (the Java11
runtime does not support these new APIs). I don't expect it to happen
anytime soon.

Jeff

**Comment by sinogermany** [comment]
Thanks for the clarification @stickfigure .

**Comment by Ki-csen** [comment]
Hi Objectify community,
I am moving to gcloud deployment from appcfg, but it throws java.lang.NoClassDefFoundError: com/google/appengine/api/datastore/AsyncDatastoreService. (Ofy 5.1.24)
Do you have any idea?  The same code works well if it is deployed by appcfg.
