### ISSUE TITLE
Datastore contention from Objectify library

### ISSUE THREAD

**Issue by LOKESH159** [objectify/objectify#460]
Hi,

Currently, we are using objectify version 5.1.23

When we try to save the entity in a transaction where we kept transaction retry as 3 times. Unfortunately, we are getting the datastore contention issue. When we checked the stack trace of the exception, the exception is getting thrown from the Objectify library.

`return ofy().transactNew(3, () -> {
   try {
       return consumer.accept(obj);
   } catch (final Exception e) {
       throw new RuntimeException(e.getMessage());
   }
});`

Please check the below image for the stack trace details.

<img width="1123" alt="Screenshot 2020-09-03 at 8 01 30 AM" src="https://user-images.githubusercontent.com/34806853/92121558-06448100-ee18-11ea-9e1d-16533168e23b.png">

**Comment by stickfigure** [comment]
I'm afraid you are mistaken - that message is generated by Google, and you're missing most of the stacktrace. TransactorNo.java line 121 is what calls your run() method (ie, your closure that calls `consumer.accept()`).

I'm not sure why your exception logger is broken, but the underlying problem is probably just plain old datastore contention. Another possibility is that your `consumer.accept()` is itself throwing `ConcurrentModificationException`, eg by iterating a collection and modifying the collection mid-stream. Unfortunately Google repurposed this common exception for datastore conflicts so user code can trigger it inadvertently.
